### ISSUE TITLE
Blog illustration for indexing file attachments

### ISSUE THREAD

**Issue by kostasb** [xataio/mdx-blog#114]
Tentative publish date: ~ Week of Sept 11 2023
PR: https://github.com/xataio/mdx-blog/pull/113

The blog post discusses processing File Attachments as raw text with the Python SDK. Some illustration of text getting out of a File and heading into a table would work (somehow indicating Python is optional)

**Comment by miukimiu** [comment]
@joan-ing the illustration. Let me know it that works.

<img width="800" alt="index-files-with-python-min" src="https://github.com/xataio/mdx-blog/assets/2750668/50e5af49-7d20-41b1-a2b0-4512962ec918">
