### ISSUE TITLE
Illustration: Community Spotlight LDO

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#163]
**Tentative Release Date:** 07 Dec

**Related post:** https://www.notion.so/xata/Community-Spotlight-Blog-Katriel-Lucas-a81becb5230b4bbaa4cfcac37b6e183d?pvs=6&utm_content=a81becb5-230b-4bba-a4cf-cac37b6e183d&utm_campaign=T025512LP5M&n=slack&n=slack_link_unfurl

**Related PR:** Coming soon

**Comment by alexfrancoeur** [comment]
linked PR: https://github.com/xataio/mdx-blog/pull/164

**Comment by alexfrancoeur** [comment]
Closing this out. I used the template. @miukimiu feel free to adjust if there's room for optimization.
