### ISSUE TITLE
Illustration: Go SDK Launch

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#166]
Blog PR: https://github.com/xataio/mdx-blog/pull/165

**Comment by alexfrancoeur** [comment]
We could have some fun with our mascot, the Go gopher and a winter holiday theme 😃

**Comment by miukimiu** [comment]
Hi @alexfrancoeur. What do you think of this illustration? 
 
<img width="800" alt="announcing-xata-go-sdk" src="https://github.com/xataio/mdx-blog/assets/2750668/25a042fe-159f-4275-9711-3b0e1e96d048">

**Comment by alexfrancoeur** [comment]
@miukimiu I love it! let's go with it

**Comment by philkra** [comment]
Awesome, thanks @miukimiu
