### ISSUE TITLE
Illustration: Holiday Hackathon

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#167]
Blog PR pending decision made here: https://xata-hq.slack.com/archives/C04PZT5HH2N/p1701725194353629

**Comment by alexfrancoeur** [comment]
Hackathon blog draft here: https://github.com/xataio/mdx-blog/pull/168

**Comment by alexfrancoeur** [comment]
@miukimiu dropped this in slack: https://www.figma.com/file/yas8z2Bgran46q1syH3kgo/Xata-Holiday-Hackathon-2023?type=design&node-id=0%3A1&mode=design&t=BB8KIuVAme5ZpYqc-1

**Comment by miukimiu** [comment]
Closed in favor of #168
