### ISSUE TITLE
Blog Illustration: On the performance of REPLICA IDENTITY FULL in Postgres

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#18]
Tentative publish date: June 7, 2023
Draft: https://www.notion.so/xata/On-the-performance-of-REPLICA-IDENTITY-FULL-in-Postgres-873e37ea86b040acb7c36b18d8ed44a2?pvs=4

**Comment by miukimiu** [comment]
### Option 1

<img width="800" alt="performance-of-replica-identity-full" src="https://github.com/xataio/mdx-blog/assets/2750668/69639535-317a-48e4-b639-6d2a35a0a472">


### Option 2

<img width="800" alt="performance-of-replica-identity-full_2" src="https://github.com/xataio/mdx-blog/assets/2750668/8bbe2fd2-8a20-4de7-9073-7266cedb42df">

**Comment by miukimiu** [comment]
Closing the issue. showed the image on Slack to Tudor and the **version one** was the picked one.

**Optimized version:**

![performance-of-replica-identity-full](https://github.com/xataio/mdx-blog/assets/2750668/cee83309-5467-449f-a217-fa5fe7401ef4)
