### ISSUE TITLE
[Illustration] Zero-downtime schema migrations in PostgreSQL

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#194]
I think we'll need a new illustration for this blog. I'm linking to the pgroll internals image now, but I imagine we don't want it to look too repetitive in the card view. Some rendition of that would probably work, or maybe we just [render it in a different color](https://www.tiktok.com/@g_man_do_css/video/7161142818444971269) 😆

https://github.com/xataio/mdx-blog/pull/193

**Comment by miukimiu** [comment]
Hey @alexfrancoeur. Here's the image for #193:
 
![postgresql-schema-migrations@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/72db5d51-ae43-46bb-8e66-99c19239edb0)

**Comment by alexfrancoeur** [comment]
amazing, thank you!
