### ISSUE TITLE
[Illustration] Holiday hackathon blog

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#196]
We're going to announce the winners for the holiday hackathon soon and feature in the monthly newsletter. This illustration could play off the original one

https://github.com/xataio/mdx-blog/pull/195

**Comment by miukimiu** [comment]
Here's the illustration for #195:

<img width="800" alt="hackathon-winners-min" src="https://github.com/xataio/mdx-blog/assets/2750668/f2216bab-ea99-467e-b4b1-c91b69a6fa69">

**Comment by alexfrancoeur** [comment]
Thank you!
