### ISSUE TITLE
[Illustration Request] Building a Retrieval-Augmented Generation Chatbot with SvelteKit and Xata Vector Search

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#204]
@miukimiu we'll need a cover image for this blog. I know you have a lot on your plate, so happy to build something off your templates and existing work in figma if you'd prefer. Ideally, we can get this out this week.

https://github.com/xataio/mdx-blog/pull/203

**Comment by alexfrancoeur** [comment]
@miukimiu I know you are heads down on the site, but if you have any bandwidth next week would it be possible to put together an illustration? if not, I can use your other templates and drop in some new logos

**Comment by miukimiu** [comment]
Working on it.

**Comment by miukimiu** [comment]
Hi @alexfrancoeur,

Here's the illustration: 


![rag-vector-sveltekit-xata-min](https://github.com/xataio/mdx-blog/assets/2750668/0ffb2117-7fa5-49c0-9c56-b092c8d550c7)

**Comment by alexfrancoeur** [comment]
@miukimiu 🙏 🙏 🙏 🙏  thank you!
