### ISSUE TITLE
[Launch Week] Exposing Postgres (aka, unleashing the Elephant 🐘 )

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#208]
Opening this issue to track the progress of the blog post for Monday the 18th

Target draft date: Thursday, February 14th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

- A good, catchy, clickable title
- An explanation for why we decided to lean more into postgres and what that means for Xata. The ecosystem, extensibility, community, etc.
    - How we think about Postgres. Great for lots of things, but not everything
- A little bit of historic context, and why it wasn’t so easy to just flip a switch (technical challenges, etc.)
- How we exposed postgres, with details around the sql proxy, what some of our limitations are, etc.
- What our plans are to take it to GA and what’s next
- Call to action to sign up, try the beta and enter the raffle

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by miukimiu** [comment]
@alexfrancoeur here's the illustration for this blog post. In case the text needs to change here's the [Figma link](https://www.figma.com/file/CoV0fcUqdSOg5sRPymlyba/blog-posts-imagery?type=design&node-id=866%3A2083&mode=design&t=hbicOB6ioy5wrJE6-1).

![lw-01-blog-postgres@2x](https://github.com/xataio/mdx-blog/assets/2750668/cabe8b52-6066-42bb-8a62-d23e8501ca46)
