### ISSUE TITLE
[Launch week] Integrating with Drizzle

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#209]
Opening this issue to track the progress of the blog post for Monday the 18th

Target draft date: Thursday, February 14th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

I think we can probably keep this simple, something similar to these blogs / sections:

https://xata.io/blog/cloudflare-integration
https://xata.io/blog/sql-over-http#kysely-integration
https://xata.io/blog/sql-over-http#drizzle-integration

At a high level, I’m think we probably want to work in a few different things

- A walk through of the integration, potentially a step by step tutorial
- Code snippets and examples, leveraging a consistent database that works well with the integration
- That this is all available with the postgres beta and some CTA to sign up

I don’t think we need much here, but the overall purpose of this one is to give Drizzle some material to cross promote.

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by alexfrancoeur** [comment]
@SferaDev I know there's a lot going on, how realistic do you think it is to have a Drizzle draft (drizzaft?) by the end of the week?

**Comment by SferaDev** [comment]
Friday morning is when I was planning to write it down hopefully 🤞🏻

**Comment by miukimiu** [comment]
@SferaDev and @alexfrancoeur here's the blog post cover:

![lw-01-blog-integrating-with-drizzle@2x](https://github.com/xataio/mdx-blog/assets/2750668/8c15db48-cbff-459e-b036-f91f6d1111eb)

**Comment by alexfrancoeur** [comment]
@SferaDev keep us in the loop with the status of that PR and let me know if it'd be helpful to have @tsg or @monicasarbu  reach out too. At the moment, we have a fair bit of content, social and website assets referencing this going out on Monday.

As for a draft of the blog, Friday works. We could make this the last blog of the day too if we don't reference it in the announcement blog

**Comment by alexfrancoeur** [comment]
If this makes it, for planning purposes can we use the slug `drizzle-postgres-xata-integration`?
