### ISSUE TITLE
[Launch Week] Integrating with Prisma

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#210]
Opening this issue to track the progress of the blog post for Monday the 18th

Target draft date: Thursday, February 14th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

I think we can probably keep this simple, something similar to these blogs / sections:

https://xata.io/blog/cloudflare-integration
https://xata.io/blog/sql-over-http#kysely-integration
https://xata.io/blog/sql-over-http#drizzle-integration

At a high level, I’m think we probably want to work in a few different things

- A walk through of the integration, potentially a step by step tutorial
- Code snippets and examples, leveraging a consistent database that works well with the integration
- That this is all available with the postgres beta and some CTA to sign up

I don’t think we need much here, but the overall purpose of this one is to give Prisma some material to cross promote.

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by miukimiu** [comment]
@eemmiillyy and @alexfrancoeur here's the blog post cover:

![lw-01-blog-integrating-with-prisma@2x](https://github.com/xataio/mdx-blog/assets/2750668/872f9e6b-5a18-4cb0-8a72-9341fcc5c465)

**Comment by alexfrancoeur** [comment]
Linking to the PR: https://github.com/xataio/mdx-blog/pull/222

**Comment by eemmiillyy** [comment]
Hey @alexfrancoeur  thanks for the feedback on the PR. Sorry about the late response on this thread, only seeing this for the first time now.
