### ISSUE TITLE
[Launch Week] New migration support and pgroll integration

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#211]
Opening this issue to track the progress of the blog post for Tuesday the 19th

Target draft date: Friday, February 15th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

- A quick introduction for why we created pgroll and plans to integrate with Xata (I can help here) with references to older content around pgroll and the repo
- A walkthrough of what the integration is and the value it provides to our users
- What's new: this is a really nice and visual addition, so the UI changes -- schema page, migration history, editor
- Things you couldn't do before: new operations now supported -- constraints, changing types, etc.
- What this looks like from code: SDK / CLI changes (or not)
- Some of the technical details: high level architecture diagrams and details around how we integrated pgroll, challenges we faced or interesting technical problems
- Plans for GA (I can also help here) -- multiple schema versions, more workflows for common operations, etc.

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by alexfrancoeur** [comment]
Still need to review in more detail, but linking to the draft that @eemmiillyy has already put together: https://www.notion.so/xata/Pgroll-Integration-Blog-Post-Rough-draft-54c2bb763af84bcf8dd26ea9c9a81c6b

**Comment by miukimiu** [comment]
@andrew-farries, @eemmiillyy and @alexfrancoeur here's the blog post cover:

![lw-02-blog-pgroll@2x](https://github.com/xataio/mdx-blog/assets/2750668/0465f6d4-47fd-42e1-a9c1-6705710816f9)

**Comment by alexfrancoeur** [comment]
Linking to the PR: https://github.com/xataio/mdx-blog/pull/221#pullrequestreview-1937909607
