### ISSUE TITLE
[Launch Week] Usage Insights

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#212]
Opening this issue to track the progress of the blog post for Wednesday the 20th

Target draft date: Friday, February 15th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

- A quick introduction as to why we needed to implement this and the value it adds
- Some of the technical choices we made and challenges we faced (and how we over came them)
- What users can expect next

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by alexfrancoeur** [comment]
@ryanslade @justshiv I know there's a lot going on before code freeze, how realistic is it to get a first draft of this blog by the end of the week?

**Comment by ryanslade** [comment]
I'll be working on a draft of the backend related stuff [here](https://www.notion.so/xata/Usage-insights-blog-76cc30fac130446190e32e85d103bb57) and hopefully will be able to dedicate a few hours to it today.

**Comment by miukimiu** [comment]
@ryanslade, @justshiv, and @alexfrancoeur here's blog post post cover:

![lw-03-blog-usage-insights@2x](https://github.com/xataio/mdx-blog/assets/2750668/b7536632-2f65-4aa7-93a5-b050145b80ed)

**Comment by ryanslade** [comment]
Blog post draft here:
https://github.com/xataio/mdx-blog/pull/224

**Comment by alexfrancoeur** [comment]
merged ✅
