### ISSUE TITLE
[Launch Week] pgzx + build in public

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#213]
Opening this issue to track the progress of the blog post for Thursday the 21st

Target draft date: Friday, March 15th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

- An introduction as to how we landed on pgzx and why we needed it
- Why we chose zig and it's benefit over other languages for extensions
- How we're using it for this project
- The technical details around how pgzx works
- Welcome contributors, ideas, etc.
- Commitment to build in public with regular monthly updates. CTA to sign up for OSS updates every month.

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by alexfrancoeur** [comment]
@tsg @urso pinging this group as a reminder that we'd like to have initial drafts in by next Friday. Tudor I know you're on a bunch of blogs, so let me know how I can help here.

**Comment by alexfrancoeur** [comment]
@tsg one thing we want to make sure we have here is the CTA to subscribe to OSS updates when we talk about build in public.

**Comment by alexfrancoeur** [comment]
Outro for the blog with the video embedded

```
Learn more about the development of this project from the folks that built it, and watch a quick demo to see it in action. Check out our latest meet the makers session here:

<ArticleVideo platform="youtube" src="https://www.youtube.com/embed/oUvAfia7gjE?si=P5ApXa2moZR3NfL8" />

Pop into [Discord](https://xata.io/discord) and say hi if you'd like to dig in further 👋

Interested in trying out for yourself? [Sign up today](https://app.xata.io/signup)! Happy building 🦋
```

**Comment by alexfrancoeur** [comment]
We'll want to add the `oss` tag here too

**Comment by alexfrancoeur** [comment]
Tagging @CezzaineZ to update the outro to match other blogs

**Comment by CezzaineZ** [comment]
> @tsg one thing we want to make sure we have here is the CTA to subscribe to OSS updates when we talk about build in public.

@tsg I am looking to set this up in Mailchimp today but wanted clarity on how we are phrasing this in the blog so it matches. "Sign up for regular OSS updates" or what should the landing page with the form say? This is what I have so far...
![Screenshot 2024-03-20 at 12 21 08](https://github.com/xataio/mdx-blog/assets/161334951/fccc9352-c09a-471e-aa1c-a08cc2853e33)

**Comment by alexfrancoeur** [comment]
I think this can be closed
