### ISSUE TITLE
[Launch Week] Dedicated Clusters EAP announcement

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#214]
Opening this issue to track the progress of the blog post for Friday the 22nd

Target draft date: Friday, February 15th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this.

- An introduction into why we needed to add dedicated clusters and how they are different than shared clusters (also reasoning around shared clusters). - Pricing advantages once GA.
- Technical details around architecture, challenges we ran into and the decisions we made
- Preview of the feature through screenshots
- Call to action to sign up for the private early access program

If anyone is interested in taking the lead on the first draft let me know. Otherwise I can help coordinate.

@miukimiu tagging you for a blog illustration

cc: @CezzaineZ

**Comment by mattfield** [comment]
@alexfrancoeur I haven't been able to make any progress on this this week due to a combo of fixes, changes and deployments. If you're happy to draft out then I can fill in the platform/infra details where relevant.

**Comment by miukimiu** [comment]
@simonapencea @mattfield @paulaguijarro and @alexfrancoeur, here's the blog post cover: 

![lw-05-blog-dedicated-clusters@2x](https://github.com/xataio/mdx-blog/assets/2750668/231b0b91-8660-45dc-bf19-53e037c1b1b0)

**Comment by alexfrancoeur** [comment]
Thanks @mattfield, I'll take a stab at a first draft tomorrow / Monday.

**Comment by simonapencea** [comment]
Ah, i forgot to also add it here: i wrote some *text* in this doc here, i had put it in the dedicated clusters slack https://docs.google.com/document/d/1Wtz8MjzFNEPO8ng-UNZVd_PB1Xxght1pZhtjenTy7i4/edit

**Comment by alexfrancoeur** [comment]
This is perfect, thank you! Will review later today

**Comment by alexfrancoeur** [comment]
Link to request access: https://5i8caik7lja.typeform.com/to/Gh5lin22

**Comment by alexfrancoeur** [comment]
Tagging @CezzaineZ to update the outro to match other blogs

**Comment by CezzaineZ** [comment]
Have requested edit access to the doc but in the meantime, if you want to add it in, it's here...

#
Learn more
Learn more about the development of this service from the folks that built it, and watch a quick demo to see it in action. Check out our latest meet the makers session here:
 <youtube link embed>

Pop into [Discord](https://xata.io/discord) and say hi if you'd like to dig in further 👋

If you don't yet have a Xata account, there's no better time to [create one](https://app.xata.io/signup)!

**Comment by simonapencea** [comment]
I think we will need more than just the outro, the introduction is also kind of lacking if you ask me

**Comment by alexfrancoeur** [comment]
Yep! dropping into the google doc soon to provide feedback, just wrapping up the video first

**Comment by alexfrancoeur** [comment]
Also, I now have the embedded link, completing the outro suggestion

```
## Learn more

Learn more about the development of this feature from the folks that built it, and watch a quick demo to see it in action. Check out our latest meet the makers session here:

<ArticleVideo platform="youtube" src="https://www.youtube.com/embed/5PtAeNkKGCE?si=PNX2ws8dI_-mBl9G" />

Pop into [Discord](https://xata.io/discord) and say hi if you'd like to dig in further 👋

If you don't yet have a Xata account, there's no better time to [create one](https://app.xata.io/signup)!
```

**Comment by alexfrancoeur** [comment]
I wasn't able to spend as much time with this draft as I'd like, but dropped in a few very minor suggestions and comments. I'll try to add more if I can, but I think we'll probably want to tap in @tsg and @exekias in for feedback and iteration.

This is an amazing start and I see a few other things we might be able to do to enhance the material:
* We have a nice UI associated with this, let's drop in some screenshots and show it off
* There are a handful of architectural diagrams, maybe @snide can help us make those look amazing
* I added a CTA at the beginning to sign up for early access in a suggestion, but we can probably sprinkle in throughout. We may want to say that EAP testers will get some sort of discounts or credits after GA to incentivize sign ups.
* Let's reference the docs wherever it makes sense
* Pricing is an advantage here for us, let's add a blurb or two about the new pricing associated with dedicated clusters
* There are postgres related advantages we want to call out vs. a shared environment

**Comment by simonapencea** [comment]
Yes please! I think we need all the help at this point. I have a hard deadline on Friday to record the QCon presentation so i cannot spend my time only on this. And there are bits and pieces that i don’t really know, maybe @mattfield can add something to the infra part. I can also move all the text into a page in this repo, but i am not sure the structure is right at this point

**Comment by mattfield** [comment]
> maybe @mattfield can add something to the infra part.

I’ll very gladly add to the infra part on Thursday morning when back at my desk.
