### ISSUE TITLE
[Launch Week] Website deep dive

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#215]
Opening this issue to track the progress of the blog post for Saturday the 23rd

Target draft date: Wednesday, February 20th

Here are my initial thoughts around the blog, though I'm sure we'll iterate a lot. Don't feel you need to stick to this in any way.

- Branding decisions made for the website
- Technical components built
- Messaging and positioning changes
- Interesting decisions made, technical challenges ran into / overcome

@miukimiu tagging you for a blog illustration (and a blog 😉)

cc: @CezzaineZ

**Comment by miukimiu** [comment]
Here's the blog post cover: 

![lw-06-blog-website-deep-dive@2x](https://github.com/xataio/mdx-blog/assets/2750668/875775c7-ea0b-4c4f-9d3a-5d6a4048b8e4)

**Comment by alexfrancoeur** [comment]
@miukimiu do you think it's feasible to have a blog post by Saturday? Half of me feels like you should just relax for the second half of the week 😆 Let me know what you think, I thought it'd be a good opportunity to highlight some fun code snippets paired with screenshots

**Comment by alexfrancoeur** [comment]
Outro for the blog with the video embedded

```
Learn more about the development of our website from the folks that built it, and watch a quick demo to see it in action. Check out our latest meet the makers session here:

<ArticleVideo platform="youtube" src="https://www.youtube.com/embed/4TOq1D3Wjho?si=LgpBSl1jm88OhsSJ" />

Pop into [Discord](https://xata.io/discord) and say hi if you'd like to dig in further 👋

Interested in trying out for yourself? [Sign up today](https://app.xata.io/signup)! Happy building 🦋
```

**Comment by alexfrancoeur** [comment]
Tagging @CezzaineZ to update the outro to match other blogs

**Comment by CezzaineZ** [comment]
> Tagging @CezzaineZ to update the outro to match other blogs

Thats the correct one so all good :)
