### ISSUE TITLE
Blog Illustration: Database schema migrations are still a PITA

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#22]
Tentative publish date: June 21, 2023
Draft: https://www.notion.so/xata/Database-schema-migrations-are-still-a-PITA-32eedfb804574d75b51fb6f8e81ca083?pvs=4

**Comment by miukimiu** [comment]
The illustration for the blog post:

<img width="800" alt="database-migrations" src="https://github.com/xataio/mdx-blog/assets/2750668/daa83237-6aea-4bac-b6d8-12b19aa8181f">

**Comment by miukimiu** [comment]
Closing this issue. The image was added in #45.
