### ISSUE TITLE
[Illustration request] Blog post on geographically distributed postgres

### ISSUE THREAD

**Issue by tsg** [xataio/mdx-blog#266]
The PR is #265  and the preview here: https://xata-blog-pr-265.vercel.app/blog/geo-distributed-postgres

I think anything with a globe and the elephant should work. Or feel free to use any of the illustrations from it.

**Comment by miukimiu** [comment]
@tsg here's the illustration:

![geo-distributed-postgres@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/ad3072ce-b386-4813-aab9-dee9e347d0f6)

**Comment by tsg** [comment]
Awesome, thanks!
