### ISSUE TITLE
[Illustration request] Tutorial blog - building a travel application

### ISSUE THREAD

**Issue by CezzaineZ** [xataio/mdx-blog#273]
Copy doc: https://docs.google.com/document/d/1nYndII6P7EU7rHPZjkt9szGKCZrXq_cu-J9jcEWWAW8/edit?pli=1#heading=h.de5xlwoszriv

Hi @miukimiu, we are planning to publish a new tutorial blog tomorrow (if possible) and I'd love your help with an illustration for /blog and the OGImage please. The copy doc is above. 

The PR I've done is broken right now so not showing a preview but hopefully the copy doc is enough for now? Let me know if you need anything else. Thank you so much.

**Comment by miukimiu** [comment]
Hi. @CezzaineZ. 

This is what I have in mind:

<img width="800" alt="travel-app" src="https://github.com/xataio/mdx-blog/assets/2750668/2c077dff-03f5-4710-85ca-08ae2531bf8c">

I'll push the image directly to #272. So I can try to fix the issues with the code snippets.

**Comment by CezzaineZ** [comment]
Thanks @miukimiu - do you think it might be good to overlay icons of some of the logos for the tools you will walk through using in the tutorial as well to match the other illustrations you've done for tutorials?

**Comment by miukimiu** [comment]
@CezzaineZ here's the new image:

<img width="800" alt="travel-app" src="https://github.com/xataio/mdx-blog/assets/2750668/dd59551c-503d-424a-86f1-619ca6e335d6">

**Comment by CezzaineZ** [comment]
Nice, thanks @miukimiu I think I prefer this one. @alexfrancoeur what do you think?

**Comment by alexfrancoeur** [comment]
I like both! If Cezzaine prefers the last one, let's roll with that.

**Comment by CezzaineZ** [comment]
@miukimiu over to you :)
