### ISSUE TITLE
[Illustration request] Heart transplant tracker community spotlight

### ISSUE THREAD

**Issue by CezzaineZ** [xataio/mdx-blog#274]
Hi @miukimiu - please can you kindly create an image for the June 13th community spotlight blog

PR: https://github.com/xataio/mdx-blog/pull/271
Preview: https://xata-blog-pr-271.vercel.app/blog/community-spotlight-heart-transplant-tracker

![PXL_20240420_212536169 (1)](https://github.com/xataio/mdx-blog/assets/161334951/7ded6cc6-dcc3-4ef1-a714-acbe5c8bf2ea)

Image attached.

Thanks :)

**Comment by miukimiu** [comment]
@CezzaineZ here's the the image:

![community-spotlight-heart-transplant-tracker-min](https://github.com/xataio/mdx-blog/assets/2750668/21006c60-6008-4e65-b6e3-be7d0e234906)

**Comment by CezzaineZ** [comment]
Looks great, thank you @miukimiu!
