### ISSUE TITLE
prisma config

### ISSUE THREAD

**Issue by wanghaisheng** [xataio/mdx-blog#277]
DATABASE_URL=`postgresql://<YOUR_WORKSPACE_ID>:<YOUR_API_KEY>@<YOUR_REGION>.sql.xata.sh:5432/<YOUR_DATABASE_NAME>:<YOUR_BRANCH_NAME>?sslmode=require`

why there is extra  .sql.xata.sh

my endpoint is https://HeisenBerg-s-workspace-8k703p.us-west-2.xata.sh/db/demo:main

**Comment by tsg** [comment]
Hi,

That is the Postgres connection string, which you can get from the Settings page of your database. The one you have looks correct:

```
postgresql://<YOUR_WORKSPACE_ID>:<YOUR_API_KEY>@<YOUR_REGION>.sql.xata.sh:5432/<YOUR_DATABASE_NAME>:<YOUR_BRANCH_NAME>?sslmode=require
```

This will use the Postgres wire protocol, which is common with Prisma. Or are you trying to use Prisma with SQL over HTTP? That might be the case if you are in a serverless env.

PS: Join us on [Discord](https://xata.io/discord), we can help better there. It was a bit of luck to notice your question here.
