### ISSUE TITLE
Port over missing blogs

### ISSUE THREAD

**Issue by alexfrancoeur** [xataio/mdx-blog#3]
There were a few blogs released between the initial port and the launch of our website. Dropping in this issue as a reminder to port them over (before or after launch).

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/25181823/233658547-2579c3ce-5451-46fb-a624-369516585878.png">

- https://xata.io/blog/community-spotlight-xata-go-sdk
- https://xata.io/blog/xata-partial-fuzzy-semantic-search
- https://xata.io/blog/ecommerce-platform-batchoop

**Comment by snide** [comment]
This is done.
