### ISSUE TITLE
Illustration for the pgstream + webhooks blog post

### ISSUE THREAD

**Issue by tsg** [xataio/mdx-blog#308]
Hi @miukimiu, we need an illustration for #304. I think it can be something simple based on the pgstream logo.

Target publish date is Aug 27.

**Comment by miukimiu** [comment]
@tsg here's the illustration:

![postgres-webhooks-with-pgstream@2x](https://github.com/user-attachments/assets/7491a910-738b-4044-94b3-212b0708784b)
