### ISSUE TITLE
Blog Illustration: Introducing the new Xata regions: Sydney & Frankfurt

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#42]
Tentative publish date: June 27, 2023
Draft: https://www.notion.so/xata/d3a65b0d3aa24414bc243e515f65992f?v=2bc37cbe76594183a2db70b008d08110&p=e4ba168d5f9142e7b799018b3084f967&pm=s 

**Image suggestions:** 
* Cover image: Globe image or map highlighting Australia and Germany 
* In blog image: Map highlighting regions where Xata is available

**Comment by miukimiu** [comment]
Starting the design for the cover image.

**Comment by miukimiu** [comment]
## Original
<img width="800" alt="xata-regions" src="https://github.com/xataio/mdx-blog/assets/2750668/eb87c1c5-d844-4966-ac9e-371cf2d9e78e">


## Optimized

<img width="800" alt="xata-regions-min" src="https://github.com/xataio/mdx-blog/assets/2750668/e3f9ab95-385c-48f2-896d-833c1f499932">
