### ISSUE TITLE
Blog Illustration: Create an advanced search engine with PostgreSQL

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#54]
Tentative publish date: June 13 , 2023
Draft: https://www.notion.so/xata/Content-Schedule-fb0ec744bc4f4a5f85d6d3b339dc618f?p=a1a80745918a4aaa82d640ac8c28283e&pm=s

**Comment by miukimiu** [comment]
@joan-ing here's the image for the blog post. Let me know if that works. 

<img width="800" alt="advanced-search-engine-with-PostgreSQL-min" src="https://github.com/xataio/mdx-blog/assets/2750668/145fa707-4d75-4950-b8fe-de08a9559143">
