### ISSUE TITLE
Blog Illustration: The Database Dilemma: SQL, MySQL, PostgreSQL, and NoSQL  - Where and When to Use Them

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#55]
Tentative publish date: June 11 , 2023
Draft: https://www.notion.so/xata/Content-Schedule-fb0ec744bc4f4a5f85d6d3b339dc618f?p=86a05936d79241b1ba5561c34cc656a8&pm=s

**Comment by miukimiu** [comment]
Hi @joan-ing,

Here's the illustration for the blog post. Let me know if the illustration works. 
 
<img width="800" alt="sql-nosql-min" src="https://github.com/xataio/mdx-blog/assets/2750668/716c914b-e20a-4c93-b324-f97a93d669da">
