### ISSUE TITLE
Blog Illustration: Create a full-text search engine with PostgreSQL, part 2: Postgres vs Elasticsearch

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#60]
Tentative publish date: June 19 , 2023
Draft: https://www.notion.so/xata/Create-a-full-text-search-engine-with-PostgreSQL-part-2-Postgres-vs-Elasticsearch-62af910470724e2db900f0a9b442dd61

**Comment by miukimiu** [comment]
@joan-ing and @tsg here's the image for the blog post:

<img width="800" alt="postgres-vs-elasticsearch" src="https://github.com/xataio/mdx-blog/assets/2750668/cd104289-c4df-49ca-a833-d6c3f847d525">
