### ISSUE TITLE
Blog Illustration: [LAUNCH] Data Ingestion CSV Imports/Exports

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#70]
Tentative publish date: Aug 28, 2023
Draft: https://www.notion.so/xata/45262135190e4d4592c089bc383b6d98

**Comment by miukimiu** [comment]
The image for #79. It's already optimized.


![csv-import-export@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/2797a139-05f3-422b-878c-2eeb8fc66526)
