### ISSUE TITLE
Blog Illustration: [LAUNCH] Language and Frameworks (Python SDK GA)

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#71]
Tentative publish date: Aug 22, 2023
Draft: https://github.com/xataio/mdx-blog/pull/69

**Comment by miukimiu** [comment]
The illustration for the blog post in #69.

![python-sdk@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/f9d21d1c-dac1-405f-a9bb-6b1ddf989267)
