### ISSUE TITLE
Blog Illustration: [LAUNCH] Data platform (Image transformation & CDN, file storage)

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#72]
Tentative publish date: August 23,2023
Draft: https://www.notion.so/xata/Wednesday-blog-post-Data-platform-3e3ac3f1bca44fbdbcc1ca4603ae75b8

**Comment by miukimiu** [comment]
The image for the blog post:

![file-attachments@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/2553fd5d-44cc-4c5b-8f33-85f070323470)
