### ISSUE TITLE
Blog Illustration: [LAUNCH] Developer Experience (JSON column)

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#74]
Tentative publish date: Sep 1, 2023
Draft: https://github.com/xataio/mdx-blog/pull/100/files

**Comment by miukimiu** [comment]
Illustration for #100:

![json-column@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/ae79fedd-5ff9-41d6-b8c3-41307821af16)
