### ISSUE TITLE
ChatGPT on your data (Part II)

### ISSUE THREAD

**Issue by joan-ing** [xataio/mdx-blog#83]
Tentative publish date: Aug 30, 2023
Draft: https://github.com/xataio/mdx-blog/pull/80

**Comment by miukimiu** [comment]
Illustration for https://github.com/xataio/mdx-blog/pull/80.

![chat-with-your-data@2x](https://github.com/xataio/mdx-blog/assets/2750668/59461541-b07c-4f3e-9ba5-cfd16fc14880)

**Comment by miukimiu** [comment]
@alexfrancoeur here's the image:

![Xata-Vercel-AI-ChatGPT@2x-min](https://github.com/xataio/mdx-blog/assets/2750668/8c811462-478f-4704-a3ed-559640da0ad3)

Since it's not part of the launch week, I adjusted the design to match the cover images of the other blog posts.
